### ISSUE TITLE
win10下无法显示弹幕内容

### ISSUE THREAD

**Issue by cncoder** [DanmakuPie/Native-Client#1]
打开客户端后，可以正常显示房号为43。但是公众号发送的内容无法弹幕出来。通过后台可以弹幕信息，证明后台可以正常接收到来自公众号的弹幕请求。为什么客户端却无法显示呢？另外你说的配置php和mysql 在哪里呢？看不到有相关配置信息。
我的弹幕π账号： cpd

**Comment by imaginezz** [comment]
很抱歉，数据库结构因为最近有些改变所以没有上传，还没来得及上传。今天或者明天会有更新
我这边测试获取弹幕是没有问题的，使用其他账号也可以在桌面上正常显示。
但是我们没法进入你的账户，所以是不是方便加一下qq 676259299 做进一步测试呢？

**Comment by cncoder** [comment]
@imaginezz  OK 加了QQ,根据情况我可以在客户端获得弹幕了，但只是一次性的获取，并不能实时更新，就是客户端登录之前信息都可以获取，但是登录之后的信息就无法实时更新出来，除非重启之后，再登录

**Comment by imaginezz** [comment]
bug已修复
